// @generated by protoc-gen-es v1.3.0 with parameter "target=ts"
// @generated from file cosmos/vesting/v1beta1/tx.proto (package cosmos.vesting.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Coin } from "../../base/v1beta1/coin_pb.js";

/**
 * MsgCreateVestingAccount defines a message that enables creating a vesting
 * account.
 *
 * @generated from message cosmos.vesting.v1beta1.MsgCreateVestingAccount
 */
export class MsgCreateVestingAccount extends Message<MsgCreateVestingAccount> {
  /**
   * @generated from field: string from_address = 1;
   */
  fromAddress = "";

  /**
   * @generated from field: string to_address = 2;
   */
  toAddress = "";

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin amount = 3;
   */
  amount: Coin[] = [];

  /**
   * @generated from field: int64 end_time = 4;
   */
  endTime = protoInt64.zero;

  /**
   * @generated from field: bool delayed = 5;
   */
  delayed = false;

  constructor(data?: PartialMessage<MsgCreateVestingAccount>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cosmos.vesting.v1beta1.MsgCreateVestingAccount";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "from_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "to_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "amount", kind: "message", T: Coin, repeated: true },
    { no: 4, name: "end_time", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "delayed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgCreateVestingAccount {
    return new MsgCreateVestingAccount().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgCreateVestingAccount {
    return new MsgCreateVestingAccount().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgCreateVestingAccount {
    return new MsgCreateVestingAccount().fromJsonString(jsonString, options);
  }

  static equals(a: MsgCreateVestingAccount | PlainMessage<MsgCreateVestingAccount> | undefined, b: MsgCreateVestingAccount | PlainMessage<MsgCreateVestingAccount> | undefined): boolean {
    return proto3.util.equals(MsgCreateVestingAccount, a, b);
  }
}

/**
 * MsgCreateVestingAccountResponse defines the Msg/CreateVestingAccount response type.
 *
 * @generated from message cosmos.vesting.v1beta1.MsgCreateVestingAccountResponse
 */
export class MsgCreateVestingAccountResponse extends Message<MsgCreateVestingAccountResponse> {
  constructor(data?: PartialMessage<MsgCreateVestingAccountResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "cosmos.vesting.v1beta1.MsgCreateVestingAccountResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgCreateVestingAccountResponse {
    return new MsgCreateVestingAccountResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgCreateVestingAccountResponse {
    return new MsgCreateVestingAccountResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgCreateVestingAccountResponse {
    return new MsgCreateVestingAccountResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgCreateVestingAccountResponse | PlainMessage<MsgCreateVestingAccountResponse> | undefined, b: MsgCreateVestingAccountResponse | PlainMessage<MsgCreateVestingAccountResponse> | undefined): boolean {
    return proto3.util.equals(MsgCreateVestingAccountResponse, a, b);
  }
}

