shulgin_mnemonic := "exclude try nephew main caught favorite tone degree lottery device tissue tent ugly mouse pelican gasp lava flush pen river noise remind balcony emerge"
shulgin := "0x6EA8AC1673402989E7B653AE4E83B54173719C30"
rpc_url := "http://127.0.0.1:8545"
chain_id := "1337"

orders: build-orders lint-orders test-orders

build-orders:
    cd orders && yarn && yarn build

lint-orders:
    cd orders && yarn lint

test-orders:
    cd orders && yarn test

localnet-orders $RPC_URL=rpc_url $CHAIN_ID=chain_id $MNEMONIC=shulgin_mnemonic $SCHEDULER_ADDRESS=shulgin $FACTORY_OWNER_ADDRESS=shulgin:
    cd orders && yarn deploy

# Example:
# just solidity create-order \
# 3324181371 \
# 0 \
# '\("ETH","USD"\)' \
# '\(100000000000000,11155111,0x467b9D1B03683C8177155Be990238bEeB1d5461f\)' \
# '\(1,[0xfff9976782d46cc05630d1f6ebab18b2324d6b14,0xb4f1737af37711e9a5890d9510c9bb60e170cb0d],0x5feAeD593ef59efEf78d97721F78c0AAC16F3dC5,1735208842\)' \
# 1 \
# 0 \
# 1000000000 \
# 0x616e7928312c2077617264656e2e73706163652e6f776e65727329 \ # <- any(1, warden.space.owners) in hex
# 0x616e7928312c2077617264656e2e73706163652e6f776e65727329 \
# 0xdee286687809c640a7d56c34cea7b8d3fcdaee2c \
# https://evm.devnet.wardenprotocol.org \
# 12345
create-order thresholdPrice priceCondition pricePair txFields swapData keyId spaceNonce actionTimeoutHeight expectedApproveExpression expectedRejectExpression $FACTORY_ADDRESS $RPC_URL=rpc_url $CHAIN_ID=chain_id $MNEMONIC=shulgin_mnemonic:
    cd orders && \
    forge script \
    --via-ir \
    --chain $CHAIN_ID \
    --skip-simulation \
    --with-gas-price 100000 \
    script/CreateOrder.s.sol:CreateOrder \
    {{thresholdPrice}} \
    {{priceCondition}} \
    {{pricePair}} \
    {{txFields}} \
    {{swapData}} \
    {{keyId}} \
    {{spaceNonce}} \
    {{actionTimeoutHeight}} \
    {{expectedApproveExpression}} \
    {{expectedRejectExpression}} \
    --sig 'run(uint256,uint8,(string,string),(uint256,uint256,address),(uint256,address[],address,uint256),uint64,uint64,uint64,bytes,bytes)' \
    --rpc-url $RPC_URL \
    --broadcast \
    -vvvv