# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json
language: "en"
early_access: false
reviews:
    request_changes_workflow: false
    high_level_summary: false
    poem: false
    review_status: false
    collapse_walkthrough: true
    path_filters:
        - "!api/**"
        - "!wardenjs/src/codegen/**"
        - "!tests/testdata/**"
    path_instructions:
        - path: "**/*.md"
          instructions: |
              "Assess the documentation for misspellings, grammatical errors, missing documentation and correctness"
    auto_review:
        enabled: true
        ignore_title_keywords:
            - "WIP"
            - "DO NOT MERGE"
        drafts: false
        base_branches:
            - "main"
chat:
    auto_reply: false
