# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
linters:
  enable-all: true
  disable:
    - cyclop
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - godox
    - gomoddirectives
    - ireturn
    - mnd
    - musttag
    - nonamedreturns
    - paralleltest
    - protogetter # to be enabled once we start moving towards Opaque API (https://go.dev/blog/protobuf-opaque)
    - recvcheck
    - tagalign
    - tenv
    - testpackage
    - varnamelen
    - wrapcheck
    
    # the followings are linters that should be enabled but the codebase
    # doesn't adhere to and we don't have enough time to fix them all at once
    - depguard
    - dupl
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocognit
    - gocritic
    - gosec
    - govet
    - inamedparam
    - lll
    - maintidx
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - stylecheck
    - tagliatelle
    - testifylint
    - thelper
    - unconvert
    - unparam
    - wsl
    - zerologlint

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "math/rand$"
            desc: use math/rand/v2
          - pkg: "github.com/sirupsen/logrus"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/warden-protocol) # Custom section: groups all imports with the specified Prefix.
      - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
    custom-order: true
  nlreturn:
    block-size: 10
  revive:
    rules:
      - name: unused-parameter
        disabled: true
      - name: var-naming
        severity: warning
        disabled: false
        exclude: [""]
        arguments:
          - ["ID", "setId"] # AllowList
          - ["VM"] # DenyList
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
