version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - dupword
    - err113
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gomoddirectives
    - gosec
    - govet
    - inamedparam
    - ireturn
    - lll
    - maintidx
    - mnd
    - musttag
    - nestif
    - nilerr
    - nilnil
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - recvcheck
    - revive
    - tagalign
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - unconvert
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
    - zerologlint
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: math/rand$
              desc: use math/rand/v2
            - pkg: github.com/sirupsen/logrus
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    exhaustive:
      default-signifies-exhaustive: true
    nlreturn:
      block-size: 10
    revive:
      rules:
        - name: unused-parameter
          disabled: true
        - name: var-naming
          arguments:
            - - ID
              - setId
            - - VM
          severity: warning
          disabled: false
          exclude:
            - ""
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        - "-SA1019"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/warden-protocol)
        - localmodule
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
