services:
  validator-1:
    build:
      context: .
      target: wardend-debug
    ports:
      - "0.0.0.0:26656:26656"
      - "0.0.0.0:26657:26657"
      - "0.0.0.0:9090:9090"
      - "0.0.0.0:1317:1317"
    environment:
      WARDEND_API_ENABLE: true
      WARDEND_API_ADDRESS: tcp://0.0.0.0:1317
      WARDEND_API_ENABLED_UNSAFE_CORS: true
      WARDEND_GRPC_ADDRESS: 0.0.0.0:9090
      WARDEND_RPC_LADDR: tcp://0.0.0.0:26657
      WARDEND_RPC_CORS_ALLOWED_ORIGINS: "*"
      WARDEND_MINIMUM_GAS_PRICES: "0uward"

  faucet:
    build:
      context: .
      target: faucet
    ports:
      - "8000:8000"
    environment:
      NODE: http://host.docker.internal:26657
      MNEMONIC: exclude try nephew main caught favorite tone degree lottery device tissue tent ugly mouse pelican gasp lava flush pen river noise remind balcony emerge

  wardenkms:
    build:
      context: .
      target: wardenkms
    environment:
      KEYCHAIN: 1
      CHAIN_ID: wardenprotocol
      MNEMONIC: exclude try nephew main caught favorite tone degree lottery device tissue tent ugly mouse pelican gasp lava flush pen river noise remind balcony emerge
      GRPC_URL: host.docker.internal:9090
      KEYRING_MNEMONIC: liberty lucky weapon argue blast borrow matrix fabric topple auto tomato age simple obvious mushroom hire edge vault federal climb step element divorce problem
      KEYRING_PASSWORD: TODO
      HTTP_ADDR: ":9999"

  spaceward:
    build:
      context: .
      target: spaceward
    ports:
      - "8080:8080"
    environment:
      FAUCET_URL: http://127.0.0.1:8000
      WARDEN_RPC_URL: http://127.0.0.1:26657
      WARDEN_REST_URL: http://127.0.0.1:1317
      ADDRESS_PREFIX: warden
      WARDEN_CHAIN_NAME: Warden Protocol (local)
      WARDEN_COSMOSKIT_CHAIN_NAME: wardenprotocollocal
      WARDEN_CHAIN_ID: warden
      WARDEN_STORYBLOK_TOKEN: LTh76K2yz5nU6jUThhFG3Qtt
