// taken from https://chainlist.org
export const ETH_RPC_URL = {
	"1": ["https://cloudflare-eth.com", "https://eth.llamarpc.com"],
	"5": ["https://rpc.goerli.mudit.blog/"],
	"10": ["https://mainnet.optimism.io/", "https://optimism.llamarpc.com"],
	"56": [
		"https://bsc-dataseed1.bnbchain.org",
		"https://binance.llamarpc.com",
	],
	"137": ["https://polygon-rpc.com/", "https://polygon.llamarpc.com"],
	"324": ["https://mainnet.era.zksync.io/"],
	"420": ["https://goerli.optimism.io"],
	"8453": ["https://mainnet.base.org/", "https://base.llamarpc.com"],
	"42161": ["https://arb1.arbitrum.io/rpc", "https://arbitrum.llamarpc.com"],
	"42220": ["https://forno.celo.org"],
	"43114": ["https://api.avax.network/ext/bc/C/rpc"],
	"44787": ["https://alfajores-forno.celo-testnet.org"],
	"80001": ["https://rpc-mumbai.maticvigil.com"],
	"81457": ["https://rpc.blast.io/"],
	"421613": ["https://goerli-rollup.arbitrum.io/rpc"],
	"7777777": ["https://rpc.zora.energy/"],
	"11155111": [
		"https://rpc.sepolia.org/",
		"wss://ethereum-sepolia-rpc.publicnode.com",
	],
};

export const ETH_CHAINID_MAP = {
	mainnet: "1",
	goerli: "5",
	optimism: "10",
	bsc: "56",
	polygon: "137",
	zksync: "324",
	optimismGoerli: "420",
	base: "8453",
	arbitrum: "42161",
	celo: "42220",
	avalanche: "43114",
	celoTestnet: "44787",
	mumbai: "80001",
	blast: "81457",
	arbitrumGoerli: "421613",
	zora: "7777777",
	sepolia: "11155111",
} as const;
