git_root := `git rev-parse --show-toplevel`
tmpdir := `mktemp -d`

all: abi

_tools:
  go install \
    github.com/ethereum/go-ethereum/cmd/abigen

abi: _tools
  cat {{git_root / "precompiles/act/abi.json"}} | jq '.abi' > {{tmpdir / "act.json"}}
  abigen --abi {{tmpdir / "act.json"}}  --pkg act --type IAct --out {{git_root / "precompiles/act/IAct.go"}}

  cat {{git_root / "precompiles/warden/abi.json"}} | jq '.abi' > {{tmpdir / "warden.json"}}
  abigen --abi {{tmpdir / "warden.json"}}  --pkg warden --type IWarden --out {{git_root / "precompiles/warden/IWarden.go"}}