import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  learn: [{type: 'autogenerated', dirName: 'learn'}],
  buildApp: [{type: 'autogenerated', dirName: 'build-an-app'}],
  buildAgent: [{type: 'autogenerated', dirName: 'build-an-agent'}],
  buildKeychain: [{type: 'autogenerated', dirName: 'build-a-keychain'}],
  operateNode: [{type: 'autogenerated', dirName: 'operate-a-node'}],
  tokens: [{type: 'autogenerated', dirName: 'tokens'}]
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
