# LEGACY DOCKERFILE. WILL REMOVE IN A FUTURE PR
FROM --platform=linux/amd64 golang:1.21-alpine3.18 AS build-env
ARG ARCH=x86_64
ARG arch=$ARCH

# Set up dependencies
ENV PACKAGES git build-base

# Set working directory for the build
WORKDIR /go/src/github.com/warden-protocol/wardenprotocol

# Install dependencies
RUN apk add --update $PACKAGES
RUN apk add linux-headers

ENV arch=$ARCH

# Add libwasmvm for musl
# Run `grep wasmvm go.mod` to find the version used in the project.
# Download checksum.txt from https://github.com/CosmWasm/wasmvm/releases to find correct checksums.
ENV WASMVM_VERSION=v1.4.0
ADD https://github.com/CosmWasm/wasmvm/releases/download/$WASMVM_VERSION/libwasmvm_muslc.aarch64.a /lib/libwasmvm_muslc.aarch64.a
ADD https://github.com/CosmWasm/wasmvm/releases/download/$WASMVM_VERSION/libwasmvm_muslc.x86_64.a /lib/libwasmvm_muslc.x86_64.a
RUN sha256sum /lib/libwasmvm_muslc.aarch64.a | grep 2a72c7062e3c791792b3dab781c815c9a76083a7997ce6f9f2799aaf577f3c25
RUN sha256sum /lib/libwasmvm_muslc.x86_64.a | grep 8ea2e3b5fae83e671da2bb51115adc88591045953f509955ec38dc02ea5a7b94

RUN cp /lib/libwasmvm_muslc.${arch}.a /lib/libwasmvm_muslc.a


## relayer-eth

FROM build-env AS relayer-eth-build
WORKDIR /warden
COPY . .
WORKDIR /warden/relayer-eth
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    go build -o relayer -tags "muslc" -ldflags '-linkmode=external -extldflags "-Wl,-z,muldefs -static"' ./cmd/relayer


FROM alpine:3.18.0 AS relayer-eth
RUN apk add --update ca-certificates jq
COPY --from=relayer-eth-build /warden/relayer-eth/relayer /usr/bin/relayer
CMD ["relayer"]

## wardend

FROM build-env AS wardend-build
WORKDIR /warden
COPY . .
WORKDIR /warden/blockchain
ENV BUILD_TAGS=muslc LINK_STATICALLY=true
RUN --mount=type=bind,source=.git,target=.git \
    --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    make build
FROM alpine:3.18.0 AS wardend
RUN apk add --update ca-certificates jq
WORKDIR /
COPY --from=wardend-build /warden/blockchain/build/wardend /usr/bin/wardend
CMD ["wardend", "start"]


## faucet

FROM alpine:3.18.0 as faucet
COPY --from=wardend-build /warden/blockchain/build/wardend /usr/bin/wardend
COPY --from=wardend-build /warden/blockchain/build/faucet /usr/bin/faucet
EXPOSE 8000
CMD ["/usr/bin/faucet"]
