# Set the working directory
FROM node:lts-alpine as web-builder
RUN npm install -g pnpm

# Read arguments
ARG BUILD_DATE
ARG GIT_SHA
ARG SERVICE

# Set env variables
ENV build_date=$BUILD_DATE
ENV commit_hash=$GIT_SHA
ENV service_name=$SERVICE
RUN echo "building service: ${service_name}, build date: ${build_date}, commit hash: ${commit_hash}"


WORKDIR /warden/web
COPY web/package*.json web/.npmrc .
RUN pnpm install
COPY web .
ENV VITE_FAUCET_URL=%FAUCET_URL%
ENV VITE_WARDEN_RPC_URL=%WARDEN_RPC_URL%
ENV VITE_WARDEN_REST_URL=%WARDEN_REST_URL%
ENV VITE_WARDEN_CHAIN_ID_NUM=%WARDEN_CHAIN_ID_NUM%
ENV VITE_WARDEN_CHAIN_ID=%WARDEN_CHAIN_ID%
ENV VITE_WARDEN_CHAIN_NAME=%WARDEN_CHAIN_NAME%
RUN pnpm run build


FROM nginx:1.25.3-alpine3.18-perl as runner
WORKDIR /var/www/app
EXPOSE 8080

COPY docker/web/entrypoint.sh /opt/entrypoint.sh
COPY docker/web/nginx.conf /etc/nginx/nginx.conf
COPY --from=web-builder /warden/web/dist .

RUN touch /var/run/nginx.pid && \
    chown -R 1000 /var/run/nginx.pid && \
    chown -R 1000 /var/cache/nginx && \
    chown -R 1000 /var/www/app && \
    chown -R 1000 /etc/nginx/conf.d/ && \
    mkdir -p /var/log/nginx && \
    mkdir -p /var/run/nginx && \
    chown -R 1000 /var/log/nginx && \
    chown -R 1000 /var/run/nginx/

USER 1000
ENTRYPOINT ["sh", "/opt/entrypoint.sh"]
CMD ["nginx-fe"]
