export interface Env {
  EVMOS_NODE_RPC: string;
  EVMOS_REGISTRY_ADDRESS: string;
  EVMOS_EVENTS_POLLING_BLOCKS: number;
  EVMOS_EVENTS_REGISTRY_START_POLLING_BLOCK: number;
  EVMOS_EVENTS_POLLING_INTERVAL_MSEC: number;
  EVMOS_CALLER_PRIVATE_KEY: string;
  ETHEREUM_NODE_RPC: string;
}
