[profile.default]
src = "src"
out = "out"
libs = ["lib"]
allow_paths = ["../../precompiles/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
