// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fusionchain/treasury/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfc42e3ec3cc822d, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfc42e3ec3cc822d, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryWalletRequestsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Types that are valid to be assigned to XStatus:
	//	*QueryWalletRequestsRequest_Status
	XStatus isQueryWalletRequestsRequest_XStatus `protobuf_oneof:"_status"`
}

func (m *QueryWalletRequestsRequest) Reset()         { *m = QueryWalletRequestsRequest{} }
func (m *QueryWalletRequestsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWalletRequestsRequest) ProtoMessage()    {}
func (*QueryWalletRequestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfc42e3ec3cc822d, []int{2}
}
func (m *QueryWalletRequestsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWalletRequestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWalletRequestsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWalletRequestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWalletRequestsRequest.Merge(m, src)
}
func (m *QueryWalletRequestsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryWalletRequestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWalletRequestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWalletRequestsRequest proto.InternalMessageInfo

type isQueryWalletRequestsRequest_XStatus interface {
	isQueryWalletRequestsRequest_XStatus()
	MarshalTo([]byte) (int, error)
	Size() int
}

type QueryWalletRequestsRequest_Status struct {
	Status WalletRequestStatus `protobuf:"varint,2,opt,name=status,proto3,enum=fusionchain.treasury.WalletRequestStatus,oneof" json:"status,omitempty"`
}

func (*QueryWalletRequestsRequest_Status) isQueryWalletRequestsRequest_XStatus() {}

func (m *QueryWalletRequestsRequest) GetXStatus() isQueryWalletRequestsRequest_XStatus {
	if m != nil {
		return m.XStatus
	}
	return nil
}

func (m *QueryWalletRequestsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *QueryWalletRequestsRequest) GetStatus() WalletRequestStatus {
	if x, ok := m.GetXStatus().(*QueryWalletRequestsRequest_Status); ok {
		return x.Status
	}
	return WalletRequestStatus_WALLET_REQUEST_STATUS_UNSPECIFIED
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*QueryWalletRequestsRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*QueryWalletRequestsRequest_Status)(nil),
	}
}

type QueryWalletRequestsResponse struct {
	Pagination     *query.PageResponse `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	WalletRequests []*WalletRequest    `protobuf:"bytes,2,rep,name=wallet_requests,json=walletRequests,proto3" json:"wallet_requests,omitempty"`
}

func (m *QueryWalletRequestsResponse) Reset()         { *m = QueryWalletRequestsResponse{} }
func (m *QueryWalletRequestsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWalletRequestsResponse) ProtoMessage()    {}
func (*QueryWalletRequestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfc42e3ec3cc822d, []int{3}
}
func (m *QueryWalletRequestsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWalletRequestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWalletRequestsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWalletRequestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWalletRequestsResponse.Merge(m, src)
}
func (m *QueryWalletRequestsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryWalletRequestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWalletRequestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWalletRequestsResponse proto.InternalMessageInfo

func (m *QueryWalletRequestsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *QueryWalletRequestsResponse) GetWalletRequests() []*WalletRequest {
	if m != nil {
		return m.WalletRequests
	}
	return nil
}

type QueryWalletRequestByIdRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryWalletRequestByIdRequest) Reset()         { *m = QueryWalletRequestByIdRequest{} }
func (m *QueryWalletRequestByIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWalletRequestByIdRequest) ProtoMessage()    {}
func (*QueryWalletRequestByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfc42e3ec3cc822d, []int{4}
}
func (m *QueryWalletRequestByIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWalletRequestByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWalletRequestByIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWalletRequestByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWalletRequestByIdRequest.Merge(m, src)
}
func (m *QueryWalletRequestByIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryWalletRequestByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWalletRequestByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWalletRequestByIdRequest proto.InternalMessageInfo

func (m *QueryWalletRequestByIdRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryWalletRequestByIdResponse struct {
	WalletRequest *WalletRequest `protobuf:"bytes,1,opt,name=wallet_request,json=walletRequest,proto3" json:"wallet_request,omitempty"`
}

func (m *QueryWalletRequestByIdResponse) Reset()         { *m = QueryWalletRequestByIdResponse{} }
func (m *QueryWalletRequestByIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWalletRequestByIdResponse) ProtoMessage()    {}
func (*QueryWalletRequestByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfc42e3ec3cc822d, []int{5}
}
func (m *QueryWalletRequestByIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWalletRequestByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWalletRequestByIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWalletRequestByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWalletRequestByIdResponse.Merge(m, src)
}
func (m *QueryWalletRequestByIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryWalletRequestByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWalletRequestByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWalletRequestByIdResponse proto.InternalMessageInfo

func (m *QueryWalletRequestByIdResponse) GetWalletRequest() *WalletRequest {
	if m != nil {
		return m.WalletRequest
	}
	return nil
}

type QueryWalletsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Types that are valid to be assigned to XWorkspaceId:
	//	*QueryWalletsRequest_WorkspaceId
	XWorkspaceId isQueryWalletsRequest_XWorkspaceId `protobuf_oneof:"_workspace_id"`
}

func (m *QueryWalletsRequest) Reset()         { *m = QueryWalletsRequest{} }
func (m *QueryWalletsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWalletsRequest) ProtoMessage()    {}
func (*QueryWalletsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfc42e3ec3cc822d, []int{6}
}
func (m *QueryWalletsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWalletsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWalletsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWalletsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWalletsRequest.Merge(m, src)
}
func (m *QueryWalletsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryWalletsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWalletsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWalletsRequest proto.InternalMessageInfo

type isQueryWalletsRequest_XWorkspaceId interface {
	isQueryWalletsRequest_XWorkspaceId()
	MarshalTo([]byte) (int, error)
	Size() int
}

type QueryWalletsRequest_WorkspaceId struct {
	WorkspaceId uint64 `protobuf:"varint,2,opt,name=workspace_id,json=workspaceId,proto3,oneof" json:"workspace_id,omitempty"`
}

func (*QueryWalletsRequest_WorkspaceId) isQueryWalletsRequest_XWorkspaceId() {}

func (m *QueryWalletsRequest) GetXWorkspaceId() isQueryWalletsRequest_XWorkspaceId {
	if m != nil {
		return m.XWorkspaceId
	}
	return nil
}

func (m *QueryWalletsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *QueryWalletsRequest) GetWorkspaceId() uint64 {
	if x, ok := m.GetXWorkspaceId().(*QueryWalletsRequest_WorkspaceId); ok {
		return x.WorkspaceId
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*QueryWalletsRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*QueryWalletsRequest_WorkspaceId)(nil),
	}
}

type QueryWalletsResponse struct {
	Pagination *query.PageResponse `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Wallets    []*Wallet           `protobuf:"bytes,2,rep,name=wallets,proto3" json:"wallets,omitempty"`
}

func (m *QueryWalletsResponse) Reset()         { *m = QueryWalletsResponse{} }
func (m *QueryWalletsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWalletsResponse) ProtoMessage()    {}
func (*QueryWalletsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfc42e3ec3cc822d, []int{7}
}
func (m *QueryWalletsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWalletsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWalletsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWalletsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWalletsResponse.Merge(m, src)
}
func (m *QueryWalletsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryWalletsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWalletsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWalletsResponse proto.InternalMessageInfo

func (m *QueryWalletsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *QueryWalletsResponse) GetWallets() []*Wallet {
	if m != nil {
		return m.Wallets
	}
	return nil
}

type QuerySignatureRequestsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Types that are valid to be assigned to XStatus:
	//	*QuerySignatureRequestsRequest_Status
	XStatus isQuerySignatureRequestsRequest_XStatus `protobuf_oneof:"_status"`
}

func (m *QuerySignatureRequestsRequest) Reset()         { *m = QuerySignatureRequestsRequest{} }
func (m *QuerySignatureRequestsRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySignatureRequestsRequest) ProtoMessage()    {}
func (*QuerySignatureRequestsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfc42e3ec3cc822d, []int{8}
}
func (m *QuerySignatureRequestsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySignatureRequestsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySignatureRequestsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySignatureRequestsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySignatureRequestsRequest.Merge(m, src)
}
func (m *QuerySignatureRequestsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySignatureRequestsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySignatureRequestsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySignatureRequestsRequest proto.InternalMessageInfo

type isQuerySignatureRequestsRequest_XStatus interface {
	isQuerySignatureRequestsRequest_XStatus()
	MarshalTo([]byte) (int, error)
	Size() int
}

type QuerySignatureRequestsRequest_Status struct {
	Status SignRequestStatus `protobuf:"varint,2,opt,name=status,proto3,enum=fusionchain.treasury.SignRequestStatus,oneof" json:"status,omitempty"`
}

func (*QuerySignatureRequestsRequest_Status) isQuerySignatureRequestsRequest_XStatus() {}

func (m *QuerySignatureRequestsRequest) GetXStatus() isQuerySignatureRequestsRequest_XStatus {
	if m != nil {
		return m.XStatus
	}
	return nil
}

func (m *QuerySignatureRequestsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *QuerySignatureRequestsRequest) GetStatus() SignRequestStatus {
	if x, ok := m.GetXStatus().(*QuerySignatureRequestsRequest_Status); ok {
		return x.Status
	}
	return SignRequestStatus_SIGN_REQUEST_STATUS_UNSPECIFIED
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*QuerySignatureRequestsRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*QuerySignatureRequestsRequest_Status)(nil),
	}
}

type QuerySignatureRequestsResponse struct {
	Pagination   *query.PageResponse `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	SignRequests []*SignRequest      `protobuf:"bytes,2,rep,name=sign_requests,json=signRequests,proto3" json:"sign_requests,omitempty"`
}

func (m *QuerySignatureRequestsResponse) Reset()         { *m = QuerySignatureRequestsResponse{} }
func (m *QuerySignatureRequestsResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySignatureRequestsResponse) ProtoMessage()    {}
func (*QuerySignatureRequestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfc42e3ec3cc822d, []int{9}
}
func (m *QuerySignatureRequestsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySignatureRequestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySignatureRequestsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySignatureRequestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySignatureRequestsResponse.Merge(m, src)
}
func (m *QuerySignatureRequestsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySignatureRequestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySignatureRequestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySignatureRequestsResponse proto.InternalMessageInfo

func (m *QuerySignatureRequestsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *QuerySignatureRequestsResponse) GetSignRequests() []*SignRequest {
	if m != nil {
		return m.SignRequests
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "fusionchain.treasury.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "fusionchain.treasury.QueryParamsResponse")
	proto.RegisterType((*QueryWalletRequestsRequest)(nil), "fusionchain.treasury.QueryWalletRequestsRequest")
	proto.RegisterType((*QueryWalletRequestsResponse)(nil), "fusionchain.treasury.QueryWalletRequestsResponse")
	proto.RegisterType((*QueryWalletRequestByIdRequest)(nil), "fusionchain.treasury.QueryWalletRequestByIdRequest")
	proto.RegisterType((*QueryWalletRequestByIdResponse)(nil), "fusionchain.treasury.QueryWalletRequestByIdResponse")
	proto.RegisterType((*QueryWalletsRequest)(nil), "fusionchain.treasury.QueryWalletsRequest")
	proto.RegisterType((*QueryWalletsResponse)(nil), "fusionchain.treasury.QueryWalletsResponse")
	proto.RegisterType((*QuerySignatureRequestsRequest)(nil), "fusionchain.treasury.QuerySignatureRequestsRequest")
	proto.RegisterType((*QuerySignatureRequestsResponse)(nil), "fusionchain.treasury.QuerySignatureRequestsResponse")
}

func init() { proto.RegisterFile("fusionchain/treasury/query.proto", fileDescriptor_dfc42e3ec3cc822d) }

var fileDescriptor_dfc42e3ec3cc822d = []byte{
	// 744 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0x41, 0x6b, 0x13, 0x41,
	0x18, 0x86, 0x33, 0xb1, 0xa6, 0x38, 0x6d, 0x53, 0x3a, 0xe6, 0x50, 0x62, 0x5d, 0xd3, 0x15, 0xda,
	0xa4, 0xc8, 0xae, 0x49, 0x4b, 0x0b, 0xe2, 0x29, 0x48, 0x6d, 0xc5, 0x43, 0xbb, 0x3d, 0x08, 0x5e,
	0x96, 0x49, 0x76, 0x5c, 0x17, 0x93, 0x9d, 0xcd, 0xce, 0xc4, 0x9a, 0xab, 0x27, 0x2f, 0x82, 0x22,
	0xe8, 0xbf, 0x10, 0x84, 0x82, 0x1e, 0xfc, 0x01, 0x3d, 0x16, 0xbd, 0x78, 0x12, 0x69, 0xfd, 0x21,
	0x92, 0x99, 0x49, 0x9b, 0x6d, 0x36, 0xc9, 0x16, 0xea, 0x2d, 0xbb, 0x79, 0xbf, 0xf9, 0x9e, 0x79,
	0x67, 0xbe, 0x37, 0x81, 0x85, 0x67, 0x6d, 0xe6, 0x51, 0xbf, 0xfe, 0x1c, 0x7b, 0xbe, 0xc9, 0x43,
	0x82, 0x59, 0x3b, 0xec, 0x98, 0xad, 0x36, 0x09, 0x3b, 0x46, 0x10, 0x52, 0x4e, 0x51, 0xae, 0x4f,
	0x61, 0xf4, 0x14, 0xf9, 0x9c, 0x4b, 0x5d, 0x2a, 0x04, 0x66, 0xf7, 0x93, 0xd4, 0xe6, 0x17, 0x5c,
	0x4a, 0xdd, 0x06, 0x31, 0x71, 0xe0, 0x99, 0xd8, 0xf7, 0x29, 0xc7, 0xdc, 0xa3, 0x3e, 0x53, 0xdf,
	0xae, 0xd4, 0x29, 0x6b, 0x52, 0x66, 0xd6, 0x30, 0x23, 0xb2, 0x85, 0xf9, 0xb2, 0x5c, 0x23, 0x1c,
	0x97, 0xcd, 0x00, 0xbb, 0x9e, 0x2f, 0xc4, 0x4a, 0xbb, 0x18, 0xcb, 0x15, 0xe0, 0x10, 0x37, 0xd9,
	0x48, 0xc9, 0x3e, 0x6e, 0x34, 0x08, 0x57, 0x12, 0x3d, 0x56, 0xd2, 0x0c, 0xea, 0xcc, 0x73, 0x55,
	0x27, 0x3d, 0x07, 0xd1, 0x6e, 0x97, 0x65, 0x47, 0xac, 0x6d, 0x91, 0x56, 0x9b, 0x30, 0xae, 0xef,
	0xc2, 0xeb, 0x91, 0xb7, 0x2c, 0xa0, 0x3e, 0x23, 0xe8, 0x1e, 0xcc, 0x48, 0x86, 0x79, 0x50, 0x00,
	0xc5, 0xa9, 0xca, 0x82, 0x11, 0xe7, 0x8e, 0x21, 0xab, 0xaa, 0x13, 0x87, 0xbf, 0x6f, 0xa5, 0x2c,
	0x55, 0xa1, 0x7f, 0x05, 0x30, 0x2f, 0xd6, 0x7c, 0x22, 0x10, 0x55, 0xa7, 0x5e, 0x47, 0xb4, 0x09,
	0xe1, 0x99, 0x0b, 0x6a, 0xf9, 0x25, 0x43, 0x5a, 0x66, 0x74, 0x2d, 0x33, 0xe4, 0xa9, 0x28, 0xcb,
	0x8c, 0x1d, 0xec, 0x12, 0x55, 0x6b, 0xf5, 0x55, 0xa2, 0x4d, 0x98, 0x61, 0x1c, 0xf3, 0x36, 0x9b,
	0x4f, 0x17, 0x40, 0x31, 0x5b, 0x29, 0xc5, 0x23, 0x46, 0x20, 0xf6, 0x44, 0xc1, 0x56, 0xca, 0x52,
	0xa5, 0x6f, 0x00, 0xa8, 0x5e, 0x83, 0x93, 0xb6, 0x7c, 0xd2, 0x0f, 0x00, 0xbc, 0x11, 0x4b, 0xae,
	0x5c, 0x79, 0x18, 0x83, 0xbe, 0x3c, 0x16, 0x5d, 0x16, 0x47, 0xd8, 0x1f, 0xc3, 0x59, 0x79, 0x7e,
	0x76, 0xa8, 0x7a, 0xcc, 0xa7, 0x0b, 0x57, 0x8a, 0x53, 0x95, 0xdb, 0x09, 0x36, 0x61, 0x65, 0xf7,
	0x23, 0x78, 0xba, 0x09, 0x6f, 0x0e, 0x52, 0x57, 0x3b, 0xdb, 0x4e, 0xcf, 0xf2, 0x2c, 0x4c, 0x7b,
	0x8e, 0xe0, 0x9d, 0xb0, 0xd2, 0x9e, 0xa3, 0x37, 0xa0, 0x36, 0xac, 0x40, 0xed, 0xf4, 0x11, 0xcc,
	0x46, 0x01, 0xd5, 0x6e, 0x13, 0xf1, 0xcd, 0x44, 0xf8, 0xf4, 0x8f, 0x40, 0xdd, 0x31, 0xa9, 0xba,
	0xf4, 0x8b, 0xb0, 0x04, 0xa7, 0xf7, 0x69, 0xf8, 0x82, 0x05, 0xb8, 0x4e, 0x6c, 0xcf, 0x11, 0xd7,
	0x61, 0x62, 0x2b, 0x65, 0x4d, 0x9d, 0xbe, 0xdd, 0x76, 0xba, 0x07, 0x3d, 0x0b, 0x67, 0xec, 0x7e,
	0xa1, 0xfe, 0x09, 0xc0, 0x5c, 0x14, 0xec, 0xb2, 0xcf, 0x79, 0x1d, 0x4e, 0x4a, 0x2f, 0x7a, 0xe7,
	0xbb, 0x30, 0xd2, 0xbf, 0x9e, 0x58, 0xff, 0x06, 0xd4, 0x91, 0xee, 0x79, 0xae, 0x8f, 0x79, 0x3b,
	0x24, 0xff, 0x6b, 0x8a, 0x1e, 0x9c, 0x9b, 0xa2, 0xe5, 0x78, 0xc0, 0x2e, 0x47, 0xb2, 0x19, 0xfa,
	0x02, 0xd4, 0xe5, 0x8a, 0x41, 0xbf, 0x6c, 0x7b, 0x37, 0xe1, 0x4c, 0x37, 0xe0, 0xce, 0x0f, 0xd1,
	0xe2, 0xd8, 0x3d, 0x58, 0xd3, 0xec, 0xec, 0x81, 0x55, 0x7e, 0x64, 0xe0, 0x55, 0xc1, 0x8c, 0xde,
	0x02, 0x98, 0x91, 0xa1, 0x86, 0x8a, 0xf1, 0xab, 0x0c, 0x66, 0x68, 0xbe, 0x94, 0x40, 0x29, 0xe9,
	0x75, 0xe3, 0xf5, 0xcf, 0xbf, 0x1f, 0xd2, 0x45, 0xb4, 0x64, 0xb6, 0x42, 0x87, 0xca, 0xbc, 0x1e,
	0xf1, 0x0b, 0x80, 0x3e, 0x03, 0x98, 0x8d, 0x86, 0x11, 0xba, 0x3b, 0xa2, 0x5b, 0x6c, 0xe2, 0xe6,
	0xcb, 0x17, 0xa8, 0x50, 0x9c, 0x1b, 0x82, 0xb3, 0x8c, 0xcc, 0x71, 0x9c, 0xe7, 0x62, 0x0c, 0x7d,
	0x07, 0x70, 0x6e, 0x20, 0x56, 0xd0, 0x6a, 0x52, 0x82, 0xbe, 0xd4, 0xca, 0xaf, 0x5d, 0xac, 0x48,
	0x91, 0xdf, 0x17, 0xe4, 0xeb, 0x68, 0xed, 0x62, 0xe4, 0x76, 0xad, 0x63, 0x7b, 0x0e, 0x7a, 0x0f,
	0xe0, 0xa4, 0x4a, 0x03, 0x54, 0x1a, 0xdb, 0xff, 0xd4, 0xe1, 0x95, 0x24, 0x52, 0x05, 0x68, 0x0a,
	0xc0, 0x12, 0x5a, 0x4e, 0x06, 0xc8, 0xd0, 0x01, 0x80, 0x73, 0x03, 0xc3, 0x34, 0xd2, 0xd2, 0x61,
	0xa9, 0x31, 0xd2, 0xd2, 0xa1, 0xf3, 0xaa, 0xaf, 0x09, 0x62, 0x03, 0xdd, 0x89, 0xe7, 0x74, 0x09,
	0xb7, 0x59, 0xaf, 0xf8, 0xf4, 0x26, 0x54, 0x77, 0x0f, 0x8f, 0x35, 0x70, 0x74, 0xac, 0x81, 0x3f,
	0xc7, 0x1a, 0x78, 0x77, 0xa2, 0xa5, 0x8e, 0x4e, 0xb4, 0xd4, 0xaf, 0x13, 0x2d, 0xf5, 0x74, 0xc3,
	0xf5, 0x78, 0x03, 0xd7, 0x8c, 0x56, 0x48, 0x1c, 0x6a, 0xd4, 0x69, 0x73, 0x88, 0x13, 0xaf, 0xce,
	0x7a, 0xf0, 0x4e, 0x40, 0x58, 0x2d, 0x23, 0xfe, 0xc9, 0xac, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0x88, 0xe5, 0x55, 0x8d, 0xcd, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of WalletRequests items.
	WalletRequests(ctx context.Context, in *QueryWalletRequestsRequest, opts ...grpc.CallOption) (*QueryWalletRequestsResponse, error)
	// Queries a single WalletRequest by its id.
	WalletRequestById(ctx context.Context, in *QueryWalletRequestByIdRequest, opts ...grpc.CallOption) (*QueryWalletRequestByIdResponse, error)
	// Queries a list of Wallets items.
	Wallets(ctx context.Context, in *QueryWalletsRequest, opts ...grpc.CallOption) (*QueryWalletsResponse, error)
	// Queries a list of SignatureRequests items.
	SignatureRequests(ctx context.Context, in *QuerySignatureRequestsRequest, opts ...grpc.CallOption) (*QuerySignatureRequestsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/fusionchain.treasury.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) WalletRequests(ctx context.Context, in *QueryWalletRequestsRequest, opts ...grpc.CallOption) (*QueryWalletRequestsResponse, error) {
	out := new(QueryWalletRequestsResponse)
	err := c.cc.Invoke(ctx, "/fusionchain.treasury.Query/WalletRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) WalletRequestById(ctx context.Context, in *QueryWalletRequestByIdRequest, opts ...grpc.CallOption) (*QueryWalletRequestByIdResponse, error) {
	out := new(QueryWalletRequestByIdResponse)
	err := c.cc.Invoke(ctx, "/fusionchain.treasury.Query/WalletRequestById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Wallets(ctx context.Context, in *QueryWalletsRequest, opts ...grpc.CallOption) (*QueryWalletsResponse, error) {
	out := new(QueryWalletsResponse)
	err := c.cc.Invoke(ctx, "/fusionchain.treasury.Query/Wallets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SignatureRequests(ctx context.Context, in *QuerySignatureRequestsRequest, opts ...grpc.CallOption) (*QuerySignatureRequestsResponse, error) {
	out := new(QuerySignatureRequestsResponse)
	err := c.cc.Invoke(ctx, "/fusionchain.treasury.Query/SignatureRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of WalletRequests items.
	WalletRequests(context.Context, *QueryWalletRequestsRequest) (*QueryWalletRequestsResponse, error)
	// Queries a single WalletRequest by its id.
	WalletRequestById(context.Context, *QueryWalletRequestByIdRequest) (*QueryWalletRequestByIdResponse, error)
	// Queries a list of Wallets items.
	Wallets(context.Context, *QueryWalletsRequest) (*QueryWalletsResponse, error)
	// Queries a list of SignatureRequests items.
	SignatureRequests(context.Context, *QuerySignatureRequestsRequest) (*QuerySignatureRequestsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) WalletRequests(ctx context.Context, req *QueryWalletRequestsRequest) (*QueryWalletRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WalletRequests not implemented")
}
func (*UnimplementedQueryServer) WalletRequestById(ctx context.Context, req *QueryWalletRequestByIdRequest) (*QueryWalletRequestByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WalletRequestById not implemented")
}
func (*UnimplementedQueryServer) Wallets(ctx context.Context, req *QueryWalletsRequest) (*QueryWalletsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Wallets not implemented")
}
func (*UnimplementedQueryServer) SignatureRequests(ctx context.Context, req *QuerySignatureRequestsRequest) (*QuerySignatureRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignatureRequests not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fusionchain.treasury.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_WalletRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWalletRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).WalletRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fusionchain.treasury.Query/WalletRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).WalletRequests(ctx, req.(*QueryWalletRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_WalletRequestById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWalletRequestByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).WalletRequestById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fusionchain.treasury.Query/WalletRequestById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).WalletRequestById(ctx, req.(*QueryWalletRequestByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Wallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWalletsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Wallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fusionchain.treasury.Query/Wallets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Wallets(ctx, req.(*QueryWalletsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SignatureRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySignatureRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SignatureRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fusionchain.treasury.Query/SignatureRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SignatureRequests(ctx, req.(*QuerySignatureRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fusionchain.treasury.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "WalletRequests",
			Handler:    _Query_WalletRequests_Handler,
		},
		{
			MethodName: "WalletRequestById",
			Handler:    _Query_WalletRequestById_Handler,
		},
		{
			MethodName: "Wallets",
			Handler:    _Query_Wallets_Handler,
		},
		{
			MethodName: "SignatureRequests",
			Handler:    _Query_SignatureRequests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fusionchain/treasury/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryWalletRequestsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWalletRequestsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWalletRequestsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XStatus != nil {
		{
			size := m.XStatus.Size()
			i -= size
			if _, err := m.XStatus.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryWalletRequestsRequest_Status) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWalletRequestsRequest_Status) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintQuery(dAtA, i, uint64(m.Status))
	i--
	dAtA[i] = 0x10
	return len(dAtA) - i, nil
}
func (m *QueryWalletRequestsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWalletRequestsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWalletRequestsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WalletRequests) > 0 {
		for iNdEx := len(m.WalletRequests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WalletRequests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryWalletRequestByIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWalletRequestByIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWalletRequestByIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryWalletRequestByIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWalletRequestByIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWalletRequestByIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WalletRequest != nil {
		{
			size, err := m.WalletRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryWalletsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWalletsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWalletsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XWorkspaceId != nil {
		{
			size := m.XWorkspaceId.Size()
			i -= size
			if _, err := m.XWorkspaceId.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryWalletsRequest_WorkspaceId) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWalletsRequest_WorkspaceId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintQuery(dAtA, i, uint64(m.WorkspaceId))
	i--
	dAtA[i] = 0x10
	return len(dAtA) - i, nil
}
func (m *QueryWalletsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWalletsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWalletsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Wallets) > 0 {
		for iNdEx := len(m.Wallets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Wallets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySignatureRequestsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySignatureRequestsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySignatureRequestsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XStatus != nil {
		{
			size := m.XStatus.Size()
			i -= size
			if _, err := m.XStatus.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySignatureRequestsRequest_Status) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySignatureRequestsRequest_Status) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintQuery(dAtA, i, uint64(m.Status))
	i--
	dAtA[i] = 0x10
	return len(dAtA) - i, nil
}
func (m *QuerySignatureRequestsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySignatureRequestsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySignatureRequestsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SignRequests) > 0 {
		for iNdEx := len(m.SignRequests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SignRequests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryWalletRequestsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.XStatus != nil {
		n += m.XStatus.Size()
	}
	return n
}

func (m *QueryWalletRequestsRequest_Status) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovQuery(uint64(m.Status))
	return n
}
func (m *QueryWalletRequestsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.WalletRequests) > 0 {
		for _, e := range m.WalletRequests {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryWalletRequestByIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryWalletRequestByIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WalletRequest != nil {
		l = m.WalletRequest.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryWalletsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.XWorkspaceId != nil {
		n += m.XWorkspaceId.Size()
	}
	return n
}

func (m *QueryWalletsRequest_WorkspaceId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovQuery(uint64(m.WorkspaceId))
	return n
}
func (m *QueryWalletsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Wallets) > 0 {
		for _, e := range m.Wallets {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QuerySignatureRequestsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.XStatus != nil {
		n += m.XStatus.Size()
	}
	return n
}

func (m *QuerySignatureRequestsRequest_Status) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovQuery(uint64(m.Status))
	return n
}
func (m *QuerySignatureRequestsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.SignRequests) > 0 {
		for _, e := range m.SignRequests {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWalletRequestsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWalletRequestsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWalletRequestsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var v WalletRequestStatus
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= WalletRequestStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.XStatus = &QueryWalletRequestsRequest_Status{v}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWalletRequestsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWalletRequestsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWalletRequestsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletRequests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WalletRequests = append(m.WalletRequests, &WalletRequest{})
			if err := m.WalletRequests[len(m.WalletRequests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWalletRequestByIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWalletRequestByIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWalletRequestByIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWalletRequestByIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWalletRequestByIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWalletRequestByIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WalletRequest == nil {
				m.WalletRequest = &WalletRequest{}
			}
			if err := m.WalletRequest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWalletsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWalletsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWalletsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkspaceId", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.XWorkspaceId = &QueryWalletsRequest_WorkspaceId{v}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWalletsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWalletsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWalletsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wallets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Wallets = append(m.Wallets, &Wallet{})
			if err := m.Wallets[len(m.Wallets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySignatureRequestsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySignatureRequestsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySignatureRequestsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var v SignRequestStatus
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= SignRequestStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.XStatus = &QuerySignatureRequestsRequest_Status{v}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySignatureRequestsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySignatureRequestsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySignatureRequestsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignRequests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignRequests = append(m.SignRequests, &SignRequest{})
			if err := m.SignRequests[len(m.SignRequests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
