# regenerate files from protobufs
codegen:
  pnpm install --ignore-scripts
  pnpm codegen

# regenerate and build wardenjs
build: codegen
  pnpm install

# release a new version on npmjs.com
release: build
  pnpm publish
