// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: warden/warden/v1beta2/keychain.proto

package v1beta2

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Keychain is an operator that can create and manage Keys.
//
// Users can request a Keychain to create a new Key using a particular scheme.
// The Keychain will store the private key, while the public key will be stored
// inside the Key object on-chain.
//
// Users can request a Keychain to sign data using a particular Key.
//
// The Keychain has an allowlist of addresses that can be used to write data
// on-chain (public keys and signatures). This can also be used to rotate the
// identity of the Keychain.
type Keychain struct {
	// ID of the Keychain.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Address of the creator of the Keychain.
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	// A human-readable description of the Keychain.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Addresses that can update this Keychain.
	Admins []string `protobuf:"bytes,4,rep,name=admins,proto3" json:"admins,omitempty"`
	// Addresses that can write data on-chain on behalf of this Keychain.
	Writers []string `protobuf:"bytes,5,rep,name=writers,proto3" json:"writers,omitempty"`
	// Fees for creating and signing Keys.
	Fees *KeychainFees `protobuf:"bytes,7,opt,name=fees,proto3" json:"fees,omitempty"`
}

func (m *Keychain) Reset()         { *m = Keychain{} }
func (m *Keychain) String() string { return proto.CompactTextString(m) }
func (*Keychain) ProtoMessage()    {}
func (*Keychain) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea6bcfb86f73f6a8, []int{0}
}
func (m *Keychain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Keychain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Keychain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Keychain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keychain.Merge(m, src)
}
func (m *Keychain) XXX_Size() int {
	return m.Size()
}
func (m *Keychain) XXX_DiscardUnknown() {
	xxx_messageInfo_Keychain.DiscardUnknown(m)
}

var xxx_messageInfo_Keychain proto.InternalMessageInfo

func (m *Keychain) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Keychain) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Keychain) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Keychain) GetAdmins() []string {
	if m != nil {
		return m.Admins
	}
	return nil
}

func (m *Keychain) GetWriters() []string {
	if m != nil {
		return m.Writers
	}
	return nil
}

func (m *Keychain) GetFees() *KeychainFees {
	if m != nil {
		return m.Fees
	}
	return nil
}

// Fees for creating and signing Keys.
type KeychainFees struct {
	// Fee for creating a new Key.
	KeyReq github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=key_req,json=keyReq,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"key_req"`
	// Fee for signing data.
	SigReq github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=sig_req,json=sigReq,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"sig_req"`
}

func (m *KeychainFees) Reset()         { *m = KeychainFees{} }
func (m *KeychainFees) String() string { return proto.CompactTextString(m) }
func (*KeychainFees) ProtoMessage()    {}
func (*KeychainFees) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea6bcfb86f73f6a8, []int{1}
}
func (m *KeychainFees) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeychainFees) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeychainFees.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeychainFees) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeychainFees.Merge(m, src)
}
func (m *KeychainFees) XXX_Size() int {
	return m.Size()
}
func (m *KeychainFees) XXX_DiscardUnknown() {
	xxx_messageInfo_KeychainFees.DiscardUnknown(m)
}

var xxx_messageInfo_KeychainFees proto.InternalMessageInfo

func (m *KeychainFees) GetKeyReq() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.KeyReq
	}
	return nil
}

func (m *KeychainFees) GetSigReq() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.SigReq
	}
	return nil
}

func init() {
	proto.RegisterType((*Keychain)(nil), "warden.warden.v1beta2.Keychain")
	proto.RegisterType((*KeychainFees)(nil), "warden.warden.v1beta2.KeychainFees")
}

func init() {
	proto.RegisterFile("warden/warden/v1beta2/keychain.proto", fileDescriptor_ea6bcfb86f73f6a8)
}

var fileDescriptor_ea6bcfb86f73f6a8 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x52, 0x31, 0x6f, 0xd4, 0x30,
	0x14, 0x3e, 0xe7, 0x8e, 0xa4, 0xf5, 0x55, 0x08, 0x22, 0x40, 0xe6, 0x86, 0x34, 0x2a, 0x0c, 0x51,
	0xa5, 0xda, 0xba, 0x63, 0x60, 0x2f, 0x52, 0x91, 0x60, 0xcb, 0xc8, 0x52, 0x39, 0xce, 0x23, 0xb5,
	0xd2, 0xc4, 0x77, 0x76, 0xa0, 0x84, 0x1f, 0xc0, 0xcc, 0xcc, 0x2f, 0x40, 0x4c, 0xfd, 0x17, 0x74,
	0xec, 0xc8, 0x04, 0xe8, 0x6e, 0xb8, 0xbf, 0x81, 0xe2, 0x38, 0xd2, 0x09, 0x31, 0xb3, 0xe4, 0xbd,
	0xcf, 0xdf, 0xf3, 0xf7, 0xc5, 0x9f, 0x1e, 0x7e, 0x7a, 0xc5, 0x75, 0x0e, 0x35, 0x73, 0xe5, 0xfd,
	0x3c, 0x83, 0x86, 0x2f, 0x58, 0x09, 0xad, 0xb8, 0xe0, 0xb2, 0xa6, 0x4b, 0xad, 0x1a, 0x15, 0x3e,
	0xec, 0x69, 0xea, 0x8a, 0x9b, 0x9a, 0xdd, 0xe7, 0x95, 0xac, 0x15, 0xb3, 0xdf, 0x7e, 0x72, 0x16,
	0x09, 0x65, 0x2a, 0x65, 0x58, 0xc6, 0x0d, 0x38, 0xb5, 0x39, 0x13, 0x6a, 0x50, 0x9a, 0x3d, 0x28,
	0x54, 0xa1, 0x6c, 0xcb, 0xba, 0xae, 0x3f, 0x3d, 0xfa, 0x8e, 0xf0, 0xde, 0x6b, 0x67, 0x19, 0xde,
	0xc5, 0x9e, 0xcc, 0x09, 0x8a, 0x51, 0x32, 0x49, 0x3d, 0x99, 0x87, 0x04, 0x07, 0x42, 0x03, 0x6f,
	0x94, 0x26, 0x5e, 0x8c, 0x92, 0xfd, 0x74, 0x80, 0x61, 0x8c, 0xa7, 0x39, 0x18, 0xa1, 0xe5, 0xb2,
	0x91, 0xaa, 0x26, 0x63, 0xcb, 0xee, 0x1e, 0x85, 0x8f, 0xb0, 0xcf, 0xf3, 0x4a, 0xd6, 0x86, 0x4c,
	0xe2, 0x71, 0xb2, 0x9f, 0x3a, 0xd4, 0x69, 0x5e, 0x69, 0xd9, 0x80, 0x36, 0xe4, 0x8e, 0x25, 0x06,
	0x18, 0x3e, 0xc7, 0x93, 0xb7, 0x00, 0x86, 0x04, 0x31, 0x4a, 0xa6, 0x8b, 0x27, 0xf4, 0x9f, 0x2f,
	0xa7, 0xc3, 0xcf, 0x9e, 0x01, 0x98, 0xd4, 0x5e, 0x78, 0x35, 0xd9, 0xf3, 0xef, 0x05, 0x47, 0x9f,
	0x3c, 0x7c, 0xb0, 0x4b, 0x86, 0x1f, 0x71, 0x50, 0x42, 0x7b, 0xae, 0x61, 0x45, 0x50, 0x3c, 0x4e,
	0xa6, 0x8b, 0xc7, 0xb4, 0x8f, 0x88, 0x76, 0x11, 0x39, 0xc1, 0x39, 0x7d, 0xa1, 0x64, 0x7d, 0x7a,
	0x76, 0xf3, 0xf3, 0x70, 0xf4, 0xed, 0xd7, 0x61, 0x52, 0xc8, 0xe6, 0xe2, 0x5d, 0x46, 0x85, 0xaa,
	0x98, 0xcb, 0xb3, 0x2f, 0x27, 0x26, 0x2f, 0x59, 0xd3, 0x2e, 0xc1, 0xd8, 0x0b, 0xe6, 0xcb, 0xf6,
	0xfa, 0xf8, 0xe0, 0x12, 0x0a, 0x2e, 0xda, 0xf3, 0x2e, 0x64, 0xf3, 0x75, 0x7b, 0x7d, 0x8c, 0x52,
	0xbf, 0x84, 0x36, 0x85, 0x55, 0xe7, 0x6d, 0x64, 0x61, 0xbd, 0xbd, 0xff, 0xe6, 0x6d, 0x64, 0x91,
	0xc2, 0xea, 0x94, 0xdf, 0xac, 0x23, 0x74, 0xbb, 0x8e, 0xd0, 0xef, 0x75, 0x84, 0x3e, 0x6f, 0xa2,
	0xd1, 0xed, 0x26, 0x1a, 0xfd, 0xd8, 0x44, 0xa3, 0x37, 0x2f, 0x77, 0x1c, 0xfa, 0x58, 0x4f, 0xec,
	0x16, 0x08, 0x75, 0xe9, 0xf0, 0x5f, 0x90, 0x7d, 0x18, 0x1a, 0x6b, 0x3f, 0x2c, 0x69, 0xe6, 0xdb,
	0xb9, 0x67, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x0b, 0x7f, 0xbc, 0xc4, 0x02, 0x00, 0x00,
}

func (m *Keychain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Keychain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Keychain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Fees != nil {
		{
			size, err := m.Fees.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintKeychain(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Writers) > 0 {
		for iNdEx := len(m.Writers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Writers[iNdEx])
			copy(dAtA[i:], m.Writers[iNdEx])
			i = encodeVarintKeychain(dAtA, i, uint64(len(m.Writers[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Admins) > 0 {
		for iNdEx := len(m.Admins) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Admins[iNdEx])
			copy(dAtA[i:], m.Admins[iNdEx])
			i = encodeVarintKeychain(dAtA, i, uint64(len(m.Admins[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintKeychain(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintKeychain(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintKeychain(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *KeychainFees) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeychainFees) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeychainFees) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SigReq) > 0 {
		for iNdEx := len(m.SigReq) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SigReq[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintKeychain(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.KeyReq) > 0 {
		for iNdEx := len(m.KeyReq) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.KeyReq[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintKeychain(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintKeychain(dAtA []byte, offset int, v uint64) int {
	offset -= sovKeychain(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Keychain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovKeychain(uint64(m.Id))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovKeychain(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovKeychain(uint64(l))
	}
	if len(m.Admins) > 0 {
		for _, s := range m.Admins {
			l = len(s)
			n += 1 + l + sovKeychain(uint64(l))
		}
	}
	if len(m.Writers) > 0 {
		for _, s := range m.Writers {
			l = len(s)
			n += 1 + l + sovKeychain(uint64(l))
		}
	}
	if m.Fees != nil {
		l = m.Fees.Size()
		n += 1 + l + sovKeychain(uint64(l))
	}
	return n
}

func (m *KeychainFees) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.KeyReq) > 0 {
		for _, e := range m.KeyReq {
			l = e.Size()
			n += 1 + l + sovKeychain(uint64(l))
		}
	}
	if len(m.SigReq) > 0 {
		for _, e := range m.SigReq {
			l = e.Size()
			n += 1 + l + sovKeychain(uint64(l))
		}
	}
	return n
}

func sovKeychain(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozKeychain(x uint64) (n int) {
	return sovKeychain(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Keychain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowKeychain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Keychain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Keychain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeychain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeychain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeychain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeychain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeychain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeychain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeychain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admins", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeychain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeychain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeychain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admins = append(m.Admins, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Writers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeychain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeychain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeychain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Writers = append(m.Writers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeychain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthKeychain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthKeychain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Fees == nil {
				m.Fees = &KeychainFees{}
			}
			if err := m.Fees.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipKeychain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthKeychain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeychainFees) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowKeychain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeychainFees: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeychainFees: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyReq", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeychain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthKeychain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthKeychain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyReq = append(m.KeyReq, types.Coin{})
			if err := m.KeyReq[len(m.KeyReq)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigReq", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeychain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthKeychain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthKeychain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SigReq = append(m.SigReq, types.Coin{})
			if err := m.SigReq[len(m.SigReq)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipKeychain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthKeychain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipKeychain(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowKeychain
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKeychain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKeychain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthKeychain
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupKeychain
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthKeychain
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthKeychain        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowKeychain          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupKeychain = fmt.Errorf("proto: unexpected end of group")
)
