---
name: Integration tests

on:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  integration-test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: Build
        run: go test -run "TestIntegration" -v ./integration_test.go
        working-directory: "tests/"