---
name: push

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  changes:
    runs-on: devops-prod
    outputs:
      blockchain: ${{ steps.filter.outputs.blockchain }}
      go-client: ${{ steps.filter.outputs.go-client }}
      mokr: ${{ steps.filter.outputs.mokr }}
      keyring: ${{ steps.filter.outputs.keyring }}
      relayer-eth: ${{ steps.filter.outputs.relayer-eth }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            blockchain:
              - 'blockchain/**'
            go-client:
              - 'go-client/**'
            mokr:
              - 'mokr/**'
            keyring:
              - 'keyring/**'
            relayer-eth:
              - 'relayer-eth/**'

  lint-blockchain:
    needs: changes
    if: ${{ needs.changes.outputs.blockchain == 'true' }}
    uses: ./.github/workflows/lint.yml
    with:
      path: "blockchain"

  test-blockchain:
    needs: changes
    if: ${{ needs.changes.outputs.blockchain == 'true' }}
    uses: ./.github/workflows/test.yml
    with:
      path: "blockchain"

  lint-go-client:
    needs: changes
    if: ${{ needs.changes.outputs.go-client == 'true' }}
    uses: ./.github/workflows/lint.yml
    with:
      path: "go-client"

  test-go-client:
    needs: changes
    if: ${{ needs.changes.outputs.go-client == 'true' }}
    uses: ./.github/workflows/test.yml
    with:
      path: "go-client"

  lint-mokr:
    needs: changes
    if: ${{ needs.changes.outputs.mokr == 'true' }}
    uses: ./.github/workflows/lint.yml
    with:
      path: "mokr"

  test-mokr:
    needs: changes
    if: ${{ needs.changes.outputs.mokr == 'true' }}
    uses: ./.github/workflows/test.yml
    with:
      path: "mokr"

  lint-keyring:
    needs: changes
    if: ${{ needs.changes.outputs.keyring == 'true' }}
    uses: ./.github/workflows/lint.yml
    with:
      path: "keyring"

  test-keyring:
    needs: changes
    if: ${{ needs.changes.outputs.keyring == 'true' }}
    uses: ./.github/workflows/test.yml
    with:
      path: "keyring"

  lint-relayer-eth:
    needs: changes
    if: ${{ needs.changes.outputs.relayer-eth == 'true' }}
    uses: ./.github/workflows/lint.yml
    with:
      path: "relayer-eth"

  test-relayer-eth:
    needs: changes
    if: ${{ needs.changes.outputs.relayer-eth == 'true' }}
    uses: ./.github/workflows/test.yml
    with:
      path: "relayer-eth"
