---
name: relayer

on:
  push:
    branches:
      - main
    paths:
      - "automated-orders/package.json"
      - "automated-orders/tsconfig.json"
      - "automated-orders/yarn.lock"
      - "automated-orders/packages/blockchain-library/**"
      - "automated-orders/packages/relayer/**"
      - "automated-orders/packages/utils-library/**"
    tags:
      - "relayer/v*"
  pull_request:
    paths:
      - "automated-orders/package.json"
      - "automated-orders/tsconfig.json"
      - "automated-orders/yarn.lock"
      - "automated-orders/packages/blockchain-library/**"
      - "automated-orders/packages/relayer/**"
      - "automated-orders/packages/utils-library/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: "automated-orders/yarn.lock"

      - name: Install dependencies
        run: yarn install
        working-directory: "automated-orders/"

      - name: Run linter
        working-directory: ./automated-orders
        run: yarn lint

      - name: TypeScript build
        working-directory: ./automated-orders
        run: tsc --build --force --verbose

  build-and-push:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/relayer/v')
    needs: [build]
    uses: ./.github/workflows/build_push.yml
    with:
      service_name: relayer
    secrets: inherit
