---
name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: ${{ matrix.release }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: ["release"]
    permissions:
      contents: write
      packages: write

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.40.0

      - name: ${{ matrix.release }}
        run: "just ${{ matrix.release }} wardend"
        env:
          RELEASE: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
